version: "3.4"
services:

  web:
    image: ss-web
    environment:
      - API_URL=${API_URL}
      - IpFilterRules=${IpFilterRules}
      - RealIpFrom=${RealIpFrom}
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    image: ss-api
    ports:
      - 5000:5000