name: API

on:
  workflow_dispatch:
env:
  IMAGE_NAME: api
  WORKING_DIRECTORY: ./
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Checkout Repo
        id: gitops
        uses: actions/checkout@v4
        
      - name: Docker Build Image
        run: |          
          docker build --tag ${{ env.IMAGE_NAME }} -f api/Dockerfile . 
          docker tag ${{ env.IMAGE_NAME }} artifacts.developer.gov.bc.ca/ccb6-images/${{ env.IMAGE_NAME }}:latest
          docker push artifacts.developer.gov.bc.ca/ccb6-images/${{ env.IMAGE_NAME }}


