name: Backup

on:
  workflow_dispatch:
env:
  IMAGE_NAME: backup
  WORKING_DIRECTORY: ./
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Checkout Schema Spy Repo
        id: gitops
        uses: actions/checkout@v4
        with:
          repository: BCDevOps/backup-container.git
          ref: master                    

      - name: Docker Build Backup Image
        run: |
          cd docker
          docker build --tag backup . 
          docker tag schema-spy artifacts.developer.gov.bc.ca/ccb6-images/${{ env.IMAGE_NAME }}:latest


