name: Build & Push Schema-Spy Image to Artifactory

on:
  workflow_dispatch:
env:
  IMAGE_NAME: schema-spy
  WORKING_DIRECTORY: ./
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Checkout Schema Spy Repo
        id: gitops
        uses: actions/checkout@v4
        with:
          repository: bcgov/SchemaSpy.git
          ref: main                    

      - name: Docker Build Schema Spy Image
        run: |
          docker build --tag schema-spy . 
          docker tag schema-spy artifacts.developer.gov.bc.ca/ccb6-images/${{ env.IMAGE_NAME }}:latest


